#!/bin/sh

VERSION=0.8.2
URL="https://sourceforge.net/projects/siproxd/files/siproxd/$VERSION/siproxd-$VERSION.tar.gz/download"
DIR="siproxd-$VERSION"

export CFLAGS="-D_GNU_SOURCE"
cd /usr/src

curl -SL "$URL" | tar xzf -

cd "$DIR"

patch -p1 < /build/siproxd-001.patch
./configure --prefix=/usr
make 
make install

cd /usr/src
rm -rf "/usr/src/$DIR"
